apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base/

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: api-rec

patches:
- path: patches/image.yaml
  target:
    group: apps
    kind: Deployment
    name: api-rec
    version: v1
