---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rec
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: api-rec
              resource: limits.memory
        image: ghcr.io/diwise/api-rec:changeme
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: api-rec
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
          - name: conf-volume
            mountPath: /opt/diwise/config
      serviceAccountName: api-rec
      volumes:
        - name: conf-volume
          configMap:
            name: rec-cfg-cm
